In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import StockHistory
import seaborn as sns
from pandas_datareader import data

In [2]:
df = StockHistory.get_namad_history_by_name("فسا",start_date='1397-1-1')
df.head()

,Date,PriceMax,PriceMin,ClosePrice,LastPrice,PriceFirst,PriceYesterday,Value,VolumeTrade,NumberTrade
GDATE,,,,,,,,,,
2018-03-25,20180325,602.0,602.0,602.0,602.0,602.0,600.0,4.274200e+07,71000,5
2018-03-26,20180326,625.0,595.0,607.0,610.0,625.0,602.0,1.491406e+09,2456288,319
2018-03-27,20180327,667.0,600.0,646.0,667.0,600.0,607.0,4.827005e+09,7472197,876
2018-03-28,20180328,695.0,671.0,682.0,680.0,687.0,646.0,7.716433e+09,11319292,1059
2018-04-03,20180403,680.0,638.0,656.0,650.0,680.0,682.0,2.758322e+09,4202311,413